### ISSUE TITLE
Flat Colour Textures

### ISSUE THREAD

**Issue by Takelmeifter** [jonpas/A3_JNS_Skycranes#11]
Got a medical sticker on it.
http://cloud-4.steamusercontent.com/ugc/38616847555091329/9D0575A6E92479727030C60DF970B16AF3663757/
http://cloud-4.steamusercontent.com/ugc/38616847555091579/9D4F989BB98129CD080CA91B16C825D676215B9C/

https://drive.google.com/folderview?id=0B2KbN1FDeTUhflpxWFVJZmc5eDZaUDd4bnY1dGR3OFNMUEI4OE5Sa2Z4YWtzbVBCdHU4UGs&usp=sharing

**Comment by Takelmeifter** [comment]
ok, standard version is up, and the special pods are up seperately
https://drive.google.com/folderview?id=0B2KbN1FDeTUhfldYRC1PYTdIUXlYcy1TTzdRRDlVLVllbExYOG5KcXRYaXdCSGpCaE1yc1E&usp=sharing

**Comment by jonpas** [comment]
Will add those in next version, thanks!

**Comment by jonpas** [comment]
Flat Grey Texture added in aa3f923d57f86c0c96d620c9e97784faa22aa1f4

**Comment by jonpas** [comment]
Thank you @Takelmeifter !
